http:
  port: 8080
admin:
  port: 9876
  host: 0.0.0.0
apiEndpoints:
  api:
    host: 0.0.0.0
    paths: "/ip"

  score_board:
    host: 0.0.0.0
    paths: "/fetchscore"

  add_score:
    host: 0.0.0.0
    paths: "/addscore"

serviceEndpoints:
  httpbin:
    url: "http://httpbin.org"

  score:
    url: "https://scoreboardservice-production-3ceb.up.railway.app/"
  add:
    url: "https://tetrisgame-production-ff2f.up.railway.app/"

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true

  scoreBoardPipeline:
    apiEndpoints:
      - score_board
    policies:
      - proxy:
          - action:
              serviceEndpoint: score
              changeOrigin: true

  addScorePipeline:
    apiEndpoints:
      - add_score
    policies:
      - proxy:
          - action:
              serviceEndpoint: add
              changeOrigin: true
